--ENTENDENDO A SINTASE DO COMANDO WHILE EM LOOP SIMPLES
/*CRIE UM LOOP QUE ACRESCENTE 1 DE VALOR A CADA REPETIÇÃO, COM NO MAXIMO 10 REPETIÇÕES*/
--DECLARANDO A VARIÁVEL 
DECLARE @VALOR INT
--DEFININDO UM VALOR INICIAL
SET @VALOR = 0
--CRIAND NOSSO LOOP
WHILE @VALOR <10
--CRIANDO UM BLOCO PARA NOSSA CONDIÇÃO OU CONDIÇÕES
BEGIN
--CONCATENANDO A PALAVRA NÚMERO, : MAIS O RESULTADO DO LOOP
	PRINT'NÚMERO: '+CAST(@VALOR AS VARCHAR(2))
SET @VALOR = @VALOR + 1
END 